// <auto-generated />
using System;
using DungeonMasterDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DungeonMasterDashboard.Migrations
{
    [DbContext(typeof(DMDbContext))]
    partial class DMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DungeonMasterDashboard.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastPlayed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DungeonMasterDashboard.Models.FifthEditionMonster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("HitPoits")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FifthEditionMonsters");
                });

            modelBuilder.Entity("DungeonMasterDashboard.Services.CyberpunkEnemy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountingSkill")
                        .HasColumnType("int");

                    b.Property<int>("ActingSkill")
                        .HasColumnType("int");

                    b.Property<int>("AirVehicleTechSkill")
                        .HasColumnType("int");

                    b.Property<int>("AnimalHandlingSkill")
                        .HasColumnType("int");

                    b.Property<int>("ArcherySkill")
                        .HasColumnType("int");

                    b.Property<int>("AthleticsSkill")
                        .HasColumnType("int");

                    b.Property<int>("AutofireSkill")
                        .HasColumnType("int");

                    b.Property<int>("BasicTechSkill")
                        .HasColumnType("int");

                    b.Property<int>("BeaurecracySkill")
                        .HasColumnType("int");

                    b.Property<int>("Body")
                        .HasColumnType("int");

                    b.Property<int>("BrawlingSkill")
                        .HasColumnType("int");

                    b.Property<int>("BriberySkill")
                        .HasColumnType("int");

                    b.Property<int>("BusinessSkill")
                        .HasColumnType("int");

                    b.Property<int>("CompositionSkill")
                        .HasColumnType("int");

                    b.Property<int>("ConcealRevealObjectSkill")
                        .HasColumnType("int");

                    b.Property<int>("ConcentrationSkill")
                        .HasColumnType("int");

                    b.Property<int>("ContortionistSkill")
                        .HasColumnType("int");

                    b.Property<int>("ConversationSkill")
                        .HasColumnType("int");

                    b.Property<int>("Cool")
                        .HasColumnType("int");

                    b.Property<int>("CriminologySkill")
                        .HasColumnType("int");

                    b.Property<int>("CryptographySkill")
                        .HasColumnType("int");

                    b.Property<int>("CurrentEmpathy")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHumanity")
                        .HasColumnType("int");

                    b.Property<int>("CybertechSkill")
                        .HasColumnType("int");

                    b.Property<string>("Cyberware")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DanceSkill")
                        .HasColumnType("int");

                    b.Property<int>("DeductionSkill")
                        .HasColumnType("int");

                    b.Property<int>("DemolitionsSkill")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("DriveLandVehicleSkill")
                        .HasColumnType("int");

                    b.Property<int>("EducationSkill")
                        .HasColumnType("int");

                    b.Property<int>("ElectronicsSecurityTechSkill")
                        .HasColumnType("int");

                    b.Property<int>("EnduranceSkill")
                        .HasColumnType("int");

                    b.Property<int>("EvasionSkill")
                        .HasColumnType("int");

                    b.Property<int>("FirstAidSkill")
                        .HasColumnType("int");

                    b.Property<int>("ForgerySkill")
                        .HasColumnType("int");

                    b.Property<int>("GambleSkill")
                        .HasColumnType("int");

                    b.Property<int>("HandgunsSkill")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeaponsSkill")
                        .HasColumnType("int");

                    b.Property<int>("HumanPerceptionSkill")
                        .HasColumnType("int");

                    b.Property<string>("InstrumentList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("InterogationSkill")
                        .HasColumnType("int");

                    b.Property<int>("LandVehicleTechSkill")
                        .HasColumnType("int");

                    b.Property<string>("LanguageList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LibrarySearchSkill")
                        .HasColumnType("int");

                    b.Property<int>("LipReadingSkill")
                        .HasColumnType("int");

                    b.Property<string>("MartialArtsList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxEmpathy")
                        .HasColumnType("int");

                    b.Property<int>("MaxHumanity")
                        .HasColumnType("int");

                    b.Property<int>("MeleeWeaponsSkill")
                        .HasColumnType("int");

                    b.Property<int>("Move")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NativeLanguageSkill")
                        .HasColumnType("int");

                    b.Property<int>("ParamedicSkill")
                        .HasColumnType("int");

                    b.Property<int>("PerceptionSkill")
                        .HasColumnType("int");

                    b.Property<int>("PersonalGroomingSkill")
                        .HasColumnType("int");

                    b.Property<int>("PersuasionSkill")
                        .HasColumnType("int");

                    b.Property<int>("PhotographyFilmSkill")
                        .HasColumnType("int");

                    b.Property<int>("PickLockSkill")
                        .HasColumnType("int");

                    b.Property<int>("PickPocketSkill")
                        .HasColumnType("int");

                    b.Property<int>("PilotAirVehicleSkill")
                        .HasColumnType("int");

                    b.Property<int>("PilotSeaVehicleSkill")
                        .HasColumnType("int");

                    b.Property<int>("Reflexes")
                        .HasColumnType("int");

                    b.Property<int>("ResistTortureDrugsSkill")
                        .HasColumnType("int");

                    b.Property<int>("RidingSkill")
                        .HasColumnType("int");

                    b.Property<string>("ScienceList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeaVehicleTechSkill")
                        .HasColumnType("int");

                    b.Property<int>("ShoulderArmsSkill")
                        .HasColumnType("int");

                    b.Property<int>("StealthSkill")
                        .HasColumnType("int");

                    b.Property<int>("StreetSlangSkill")
                        .HasColumnType("int");

                    b.Property<int>("StreetwiseSkill")
                        .HasColumnType("int");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TacticsSkill")
                        .HasColumnType("int");

                    b.Property<int>("Tech")
                        .HasColumnType("int");

                    b.Property<int>("TrackingSkill")
                        .HasColumnType("int");

                    b.Property<int>("TradingSkill")
                        .HasColumnType("int");

                    b.Property<int>("WardrobeAndStyleSkill")
                        .HasColumnType("int");

                    b.Property<int>("WeaponstechSkill")
                        .HasColumnType("int");

                    b.Property<int>("WildernessSurvivalSkill")
                        .HasColumnType("int");

                    b.Property<int>("Willpower")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CyberpunkEnemies");
                });
#pragma warning restore 612, 618
        }
    }
}
